### ISSUE TITLE
unsupported operand type(s)

### ISSUE THREAD

**Issue by gxfasd** [HolyWu/vs-swinir#4]
I used 2.0:
script:

> ret= core.lsmas.LWLibavSource(r'D:\video\VapourSynth64Portable\1.mp4') core.resize.Bicubic(ret, format=vs.RGBS,dither_type="error_diffusion")  
ret =SwinIR(ret,model=0)
  ret = core.resize.Bicubic(ret, format=vs.YUV420P16, matrix_s="709", range_s="full")   
ret = core.resize.Bicubic(ret, format=vs.YUV420P8,matrix_s="709",range_s="full")    
ret.set_output()> 

result:

> Failed to evaluate the script: Python exception: unsupported operand type(s) for //: 'vapoursynth.VideoNode' and 'int'  Traceback (most recent call last): File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate File "D:/video/VapourSynth64Portablevb/swinir2.vpy", line 46, in  ret =SwinIR(ret,model=0) File "D:\video\VapourSynth64Portablevb\VapourSynth64\Lib\site-packages\vsswinir\network_swinir.py", line 561, in __init__ self.patch_embed = PatchEmbed( File "D:\video\VapourSynth64Portablevb\VapourSynth64\Lib\site-packages\vsswinir\network_swinir.py", line 406, in __init__ patches_resolution = [img_size[0] // patch_size[0], img_size[1] // patch_size[1]] TypeError: unsupported operand type(s) for //: 'vapoursynth.VideoNode' and 'int'> 

but 1.0 is ok!

**Comment by HolyWu** [comment]
The function name in v2.0 is `swinir` in lowercase. Sorry for forgetting to mention it in the release note.
